databases:
  - name: users-db
    databaseName: users_db
    user: users_admin
    plan: free

services:
  - type: web
    name: users-management-api
    runtime: docker
    plan: free
    branch: main
    autoDeployTrigger: commit
    healthCheckPath: /v3/api-docs
    dockerfilePath: ./Dockerfile
    envVars:
      - key: PORT
        value: "8080"
      - key: DB_TYPE
        value: postgresql
      - key: DATASOURCE_URL
        fromDatabase:
          name: users-db
          property: connectionString
      - key: DATASOURCE_USERNAME
        fromDatabase:
          name: users-db
          property: user
      - key: DATASOURCE_PASSWORD
        fromDatabase:
          name: users-db
          property: password
      - key: MAIL_HOST
        value: smtp.gmail.com
      - key: MAIL_PORT
        value: "587"
      - key: MAIL_USERNAME
        sync: false
      - key: MAIL_PASSWORD
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_EXPIRATION_SECONDS
        value: "900"
